### ISSUE TITLE
UPDATED for Xcode 7 - Swipe function doesn't work on iOS Simulators < 9.0

### ISSUE THREAD

**Issue by rpranata** [calabash/calabash-ios#253]
It might be related to this issue (https://github.com/calabash/calabash-ios/issues/230) however I tried it on the normal orientation and it still doesnt work.

Reproduction steps:
1. Open console with: 
    `DEBUG=1 CALABASH_FULL_CONSOLE_OUTPUT=1 calabash-ios console`
2. Then on the console, start the server from the instruments, with: 
     `start_test_server_in_background`
3. Make sure that there is a scrollView (or my case collectionView) on the screen.
    `query "collectionView"` yields a result with this description

```
<UICollectionView: 0xdb74200; frame = (0 0; 320 568); opaque = NO; 
autoresize = W+H; gestureRecognizers = <NSArray: 0xd1b86c0>; 
layer = <CALayer: 0xd1e2a30>; contentOffset: {320, 0}> 
collection view layout: 
<MTCardViewFlowLayout: 0xd1ab400>\n          
    Current Page: 1\n          
    Max Page: 7\n
```
1. Swipe with this command:
   `swipe "right", {:query => "collectionView"}` results in this log:
   
   `Sending UIA command`
   `uia.swipeOffset('{:x 160, :y 284}', '{:query "collectionView", :direction :right}')`
   `Result`
   `{"status"=>"success", "value"=>":nil", "index"=>0}`

Which I assume should go to success but nothing happens on the simulator. Everything else works tho, like touch, scroll but not swipe.

I also found this issue on the Apple Developer Forum (https://devforums.apple.com/message/901404#901404), but since I dont know what UIA method the `swipe` translates to, Im not 100% sure that it is related.

---

Cheers,
Rendy Pranata

**Comment by houbena** [comment]
Is this swipe issue still persisting or is there already a fix?

**Comment by jmoody** [comment]
No fix.   We have to wait for Apple to fix their UIAutomation API.

**Comment by houbena** [comment]
Thanks for the quick answer .. Is there any alternative?

**Comment by mcostanzo1** [comment]
hi
I need to know if there is any alternative to using the scroll .

I'm using iOS 7.1 simulator .
Xcode 5.1.1

thank you very much

**Comment by caioborges** [comment]
@mcostanzo1  Then I swipe up/down/left/right

**Comment by alexblack** [comment]
Anyone got a work around for iOS 8.x in simulator?

**Comment by jmoody** [comment]
@alexblack Nope.  It is completely broken.  We haven't tried Xcode 7/iOS 9.

**Comment by mcostanzo1** [comment]
friends!
currently I have version 5.1.1 of Xcode and scroll works well on 7.1 iOS
iPad simulator.
I use this line in my ruby code for example:

scroll "scrollView index: 2", :down





2015-08-06 3:37 GMT-03:00 Joshua Moody <notifications@github.com>:

**Comment by jmoody** [comment]
@mcostanzo1 scroll has always worked.

:8ball: 

What doesn't work is UIAutomation `dragInsideWithOptions` and `flickInsideWithOptions` which is what _swipe_ uses under the hood.

I am looking for a PR that can swipe-to-delete a table view row programmatically.

**Comment by mcostanzo1** [comment]
okay, sorry for my mistake.
I thought they were talking about the scroll.

dismiss the previous comment

2015-08-06 12:33 GMT-03:00 Joshua Moody <notifications@github.com>:

**Comment by amast09** [comment]
@jmoody we are getting flaky failures when using the pan gesture.

```
Timed out running command uia.panOffset('{:x 722, :y 250.5}', '{:x 196.5, :y 82.5}', '{}')
```

We get this error randomly once in every 30-40 runs of our test suite.  Have people been experiencing drag and drop issues or do you think it is an issue with our usage of the pan function?

Thanks a million for any kind of help you can provide us!

**Comment by jmoody** [comment]
@amast09 Can you open a new issue re: pan?  Please include details about the Xcode version and Calabash version.

https://github.com/calabash/calabash-ios/wiki#reporting-problems

FWIW, I haven't seen problems with pan yet expect that pan no longer works to change iPad keyboard modes.

**Comment by jmoody** [comment]
**UPDATE** In Xcode 7's iOS 9 simulators, swiping appears fixed.

```
var target = UIATarget.localTarget();

target.setDeviceOrientation(UIA_DEVICE_ORIENTATION_PORTRAIT);

target.delay(1)

target.frontMostApp().tabBar().buttons()["Scrolling Views"].tap();

target.delay(1)

target.frontMostApp().mainWindow().elements()["scrolling views home"].tableViews()["table"].tapWithOptions({tapOffset:{x:0.25, y:0.15}});

target.delay(1)

var start = {x:0.90, y:0.44}
var end = {x:0.10, y:0.44}
var options = {startOffset:start, endOffset:end, duration:1.0}

target.frontMostApp().mainWindow().elements()["alphabet"].tableViews()["table"].dragInsideWithOptions(options)
```

**Comment by jmoody** [comment]
Filed a radar: 22869151

## Report

Xcode 7 iOS 8 simulators UIAutomation dragInsideWithOptions cannot swipe to delete table view cells

### Summary:

Since Xcode 6, UIAutomation dragInsideWithOptions has been broken for the swipe gesture on iOS >= 7 Simulators.

This has been widely reported.

* http://stackoverflow.com/questions/18792965/uiautomations-draginsidewithoptions-has-no-effect-on-ios7-simulator
* http://stackoverflow.com/questions/31402610/how-to-simulate-touch-or-swipe-in-ios-7-8
* https://discuss.appium.io/t/swipe-actions-are-not-performed-in-simulator/994
* https://github.com/calabash/calabash-ios/issues/253

In Xcode 7 and Xcode 7.1 betas, dragInsideWithOptions works for iOS >= 9 simulators.

However, dragInsideWithOptions is still broken when targeting iOS < 9 simulators.

### Steps to Reproduce:

1. Install the attached app on an Xcode 7, iOS 8 simulator
2. Launch the Instruments.app and target the simulator and app from step 1
3. Run the following JavaScript

var target = UIATarget.localTarget();

target.setDeviceOrientation(UIA_DEVICE_ORIENTATION_PORTRAIT);

target.delay(1)

target.frontMostApp().tabBar().buttons()["Scrolling Views"].tap();

target.delay(1)

target.frontMostApp().mainWindow().elements()["scrolling views home"].tableViews()["table"].tapWithOptions({tapOffset:{x:0.25, y:0.15}});

target.delay(1)

var start = {x:0.90, y:0.44}
var end = {x:0.10, y:0.44}
var options = {startOffset:start, endOffset:end, duration:1.0}

target.frontMostApp().mainWindow().elements()["alphabet"].tableViews()["table"].dragInsideWithOptions(options)

### Expected Results:

Expected to see the 'Delete' button appear (as in the screenshot).

### Actual Results:

No gesture is performed or the row is touched.

**Comment by jjacquet** [comment]
i am also trying to get under the hood a UITableViewCell i need an offset swipe, but nothing seems to be happening. I'm using Xcode 6.4

`swipe :left, :query => "UIImageView index:13", :offset => {:x => -100, :y => 0}, :"swipe-delta" => {:horizontal => {:dx=> 200, :dy=> 0} }`

 When I perform this swipe query in the irb console it doesn't complain, but again nothing happens.

**Comment by jmoody** [comment]
@jjacquet It will not work on any iOS Simulator < 9.0.  It is just broken.  Apple is aware of the problem.

**Comment by jjacquet** [comment]
Thanks for the quick repose @jmoody So were all on hold until this is addressed? This is a major roadblock for my team. I do have high hopes for Apples next generation of XCTests in Swift, but in the meantime this kind of a bummer

**Comment by jmoody** [comment]
@jjacquet

My only advice is to run on devices or iOS 9.* simulators. 

> In your new title of this posting "...Swipe function doesn't work on iOS Simulators < 9.0". Are you saying it works on 9.0>?

>= 9.0.  Otherwise, correct.

**Comment by jjacquet** [comment]
I've updated one of my machine to Xcode 7.0.1 using a 9.0 sim. Now when I put in the ship method I am getting an undefined method 'error'. Has the syntax changed?

` swipe :left, :query => "UILabel marked: 'testAutomationPlaylist'", :offset => {:x => -100, :y => 0}, :"swipe-delta" => {:horizontal => {:dx=> 200, :dy=> 0} }
NoMethodError: undefined method `swipe' for nil:NilClass
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/core.rb:359:in `swipe'
	from (irb):2
	from /usr/bin/irb:12:in `<main>'`

**Comment by jjacquet** [comment]
Hi @jmoody I still can get the swipe to work. Do think this could be an issue?

```WARN: The server version is not compatible with gem version.
Please update your server.
https://github.com/calabash/calabash-ios/wiki/B1-Updating-your-Calabash-iOS-version
       gem version: '0.16.4'
min server version: '0.16.4'
    server version: '0.16.2' ```

**Comment by jmoody** [comment]
@jjacquet

> Now when I put in the swipe method I am getting an undefined method 'error'.

In the console ($ calabash-ios console), you must allow calabash to launch the app before you perform any gestures.

```
$ bundle exec calabash-ios console
> start_test_server_in_background
```
> The server version is not compatible with gem version

This warning should not have any bearing on swipe.  However, you should update the server or use a Gemfile to pin the Calabash gem version to 0.16.2.

* [Updating your Calabash iOS version](https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version)
* [Best Practice: Use Gemfile and bundler](https://github.com/calabash/calabash-ios/wiki/Best-Practice%3A-Use-Gemfile-and-bundler)

**Comment by mendirattanishant** [comment]
I am still not able to swipe with iOS sim 9.1 and calabash 0.16.4 It says "undefined method `swipe' for nil:NilClass". Has this been resolved?

**Comment by jmoody** [comment]
@mendirattanishant Where is this happening?  In cucumber tests or on the console?

**Comment by mendirattanishant** [comment]
@jmoody  It says on the console

**Comment by jmoody** [comment]
Please open a new issue.  This has nothing to do with the problem described here. In the new issue please:

* describe how you are starting the console
* if you have a custom .irbrc, please paste into the issue

**Comment by eearif** [comment]
hey Guys,  why are we always lagging behind with calabash ios issues,
Swipes, don't work,  touch does not work.  
accessibility labels don't work. 
I want us to ramp up the speed and be the first in delivering the best automation framework for ios 
outbeating appium and others.

**Comment by eearif** [comment]
@jmoody  can you please explain why calabash-ios is slowly becoming outdated and redundant; 
there was a time when appium was struggling with ios and it was a big pain . Now they are providing much better features and functionalities for both apps and mobile web support .
Why is calabash -ios behind,  can u please discuss the roadmap and ramp up the speed . 
Please let us know , as we are highly dependant on calabash-ios .

**Comment by krukow** [comment]
@eearif - Your comment is plain wrong and not appreciated. Your message is pure [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt). Touches, swipes and all gestures work as do all other features in Calabash. Calabash is neither outdated nor redundant, in-fact Calabash has been more active than appium over the last few months ([Appium commits](https://github.com/appium/appium/graphs/commit-activity) vs [Calabash iOS commits](https://github.com/calabash/calabash-ios/graphs/commit-activity) although while comparing commits isn't very meaningful it does say something about activity). 

Calabash is not lagging behind, but is accelerating: we're close to a major 2.0 release and we're building out new very powerful features as part of that.

I'm not sure what your intent is with these comments, but I consider them malicious and non constructive. 
If you are experiencing issues please just create a new issue rather than hijacking an existing different issue. Please follow the guide for reporting issues (with examples of good reports): https://github.com/calabash/calabash-ios/wiki#reporting-problems 

If you want to test pure browser web-apps use Appium, Calabash is targeting web apps.

If you're looking for a roadmap please see:

https://groups.google.com/d/msg/calabash-ios/KeamyYqVHNQ/mx9TGg-B700J 
and note that we're working XCUITest support.
