### ISSUE TITLE
undefined local variable or method `start_test_server_in_background' in calabash-ios 0.12.0

### ISSUE THREAD

**Issue by tomaszmnich** [calabash/calabash-ios#669]
Since I've update calabash-ios to v0.12.0 I cannot start-up console via: calabash-ios console and then start_test_server_in_background:

tomasz.mnich$ calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
NameError: undefined local variable or method `start_test_server_in_background' for main:Object
from (irb):1
from /usr/bin/irb:12:in `<main>'
irb(main):002:0> 

Xcode : 6.1
SDK version: 8.1
iOS: 8.1
mac OSX : 10.9.5 
Calabash-ios client : 0.12.0
Calabash-ios server: 0.12.0

**Comment by jmoody** [comment]
@tomaszmnich Are you using rvm?

If so, the cause of this problem is that rvm defines the IRBRC variable to be ~/.irbrc and calabash requires a different `.irbrc.`

You can try:

```
$ IRBRC= calabash-ios console
```

or

```
$ unset IRBRC
$ calabash-ios console
```

**Comment by sasjo** [comment]
I got the same problem. I'm suspecting I'm doing something wrong while upgrading calabash-ios from 11.4 to 12.0. I started out with the manual (gem install) approach but have also tried bundler afterwards.

My tests fail on wait_tap and the console doesn't know about any calabash API commands. When I try to manually include the calabash_steps I get this:

```
irb(main):002:0> require 'calabash-cucumber/calabash_steps'
Gem::ConflictError: Unable to activate calabash-cucumber-0.12.0, because awesome_print-1.6.1 conflicts with awesome_print (~> 1.2.0)
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1280:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:198:in `rescue in try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:195:in `try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):2
	from /usr/bin/irb:12:in `<main>'
irb(main):003:0> 
```

I'm sure there's something wrong in the way I've upgraded the gems, but have no clue where to start to solve it.

**Comment by tomaszmnich** [comment]
@jmoody  Unfortunately, your solution which unset IRBRC at the time I'm using calabash console is not working. Issue still exists.

**Comment by sasjo** [comment]
I got things working with 0.12 after uninstalling the awesome_print gem version 1.6.0 which for some reason had been installed. I think I might have caused the problems by installing the run_loop 1.2.2 gem instead of 1.2.1. So what I did was `sudo gem uninstall awesome_print` and choosing to remove version 1.6.0. I also removed old versions of run_loop and calabash_cucumber.  After that `calabash-ios console` works out-of-the-box.

**Comment by tomaszmnich** [comment]
@sasjo - great answer, cheers! 
So the issue was related with the awsome_print gem (in my case v.1.6.1 - I haven't notice gem upgrade in the meantime btw). After "sudo gem uninstall awesome_print -v1.6.1" and back to awesome_print v1.2.0 calabash-ios console is now working again.
Thanks a lot.

**Comment by jmoody** [comment]
@sasjo @tomaszmnich 

Ah, I see the problem.

The problem is that one of the require statements in the calabash .irbrc was failing (silently) which stops the evaluation of the .irbrc, so the calabash-ios gem methods were not loaded.

Good answer.

**Comment by tomaszmnich** [comment]
run_loop gem v1.2.2 requires awesome_print gem in v1.6.0. So I've switched again to run_loop v.1.2.1 to make things work again.

**Comment by jaguar01** [comment]
I can't get this working with 0.12.3

awesome_print (1.6.1, 1.6.0)
run_loop (1.2.6, 1.2.1)
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
$ xcodebuild -version
Xcode 6.1.1
Build version 6A2008a
$ calabash-ios version
0.12.3
$ curl http://10.10.1.100:37265/version
{"app_id":"com.philips.cl.di.dev.purair.beta","outcome":"SUCCESS","server_port":37265,"version":"0.12.3","app_name":"Smart Air","system":"iPhone6,2","simulator_device":"","simulator":"","app_version":"1.35.1","iphone_app_emulated_on_ipad":false,"git":{"revision":"2cd99dd","remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master"},"screen_dimensions":{"sample":1,"height":1136,"width":640,"scale":2},"4inch":true,"iOS_version":"8.1.2"


$ DEVICE_ENDPOINT=http://10.10.1.100:37265 APP_BUNDLE_PATH=/Users/<PATH TO .xcodeproj> calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
NameError: undefined local variable or method `escaped_binary_path' for #<RunLoop::Lipo:0x007fa4c402b398>

**Comment by jmoody** [comment]
@jaguar01 

> `DEVICE_ENDPOINT=http://10.10.1.100:37265 APP_BUNDLE_PATH=/Users/`

It looks like you are targeting a physical device.  If this is the case, `APP` or `APP_BUNDLE_PATH` does not make sense.  You need to specify `BUNDLE_ID`.

Also, you seem to be missing the full path to your .app, but maybe you just omitted it?

In any event, you should probably not be seeing this error.

My guess is that you are not running the correct version of some gem.  We recommend using bundler.

```
# In the directory with your Gemfile

$ bundle install

# Start the console in the context of bundle exec.
$ DEVICE_ENDPOINT=http://10.10.1.100:37265 BUNDLE_ID=com.your.app bundle exec calabash-ios console
```

In the future, please use Markdown formatting in your issue.

This issue *might* be related to the original topic, but a look at the error message shows it does not match the title of this issue.  If the advice above does not fix your problem, please open a new issue.

```
irb(main):001:0> start_test_server_in_background
NameError: undefined local variable or method `escaped_binary_path' for 
```

**Comment by jaguar01** [comment]
Confirmed it is not this issue (and no issue at all). Following instructions using BUNDLE_ID and removing APP_BUNDLE_PATH another message is displayed (Errno::EINTR). I runned the sample-script.js and it turns out that the app must be signed with a development identity. (using bundle did not make a difference). Thanks a lot.
