### ISSUE TITLE
calabash-ios console doesn't work in 0.19.0.pre2

### ISSUE THREAD

**Issue by svandeven** [calabash/calabash-ios#1064]
I installed 0.19.0.pre2 and now I get 
```
 $ calabash-ios console
Running irb...
irb(main):001:0> query("*")
NoMethodError: undefined method `query' for main:Object
	from (irb):1
	from /opt/boxen/rbenv/versions/2.2.2/bin/irb:11:in `<main>'
irb(main):002:0>
```
I rolled back to 0.18.2 version and query worked again in the console.

**Comment by jmoody** [comment]
Ugh.  I cannot reproduce locally.

I know what the problem is likely to be however.  Anyone up for a tmate session?

**Comment by svandeven** [comment]
if only I could!  If you want to do the screen sharing again I can show you

**Comment by JoeSSS** [comment]
I can show you too

**Comment by jmoody** [comment]
@JoeSSS and @svandeven I am available on Gitter to coordinate some kind of screen sharing.

https://gitter.im/calabash/calabash0x?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jmoody** [comment]
Thank you @JoeSSS  for the tmate session.

The problem is that .irbrc file is not part of the gem.  I don't know why.

The workaround is to create a local .irbrc file (in the directory where you run `calabash-ios console`) with the following contents:

```
require 'rubygems'
require 'irb/completion'
require 'irb/ext/save-history'

begin
  require 'awesome_print'
rescue LoadError => e
  msg = ["Caught a LoadError: could not load 'awesome_print'",
         "#{e}",
         '',
         'Use bundler (recommended) or uninstall awesome_print.',
         '',
         '# Use bundler (recommended)',
         '$ bundle update',
         '$ bundle exec calabash-ios console',
         '',
         '# Uninstall',
         '$ gem update --system',
         '$ gem uninstall -Vax --force --no-abort-on-dependent awesome_print']
  puts msg
  exit(1)
end

AwesomePrint.irb!

ARGV.concat [ '--readline',
              '--prompt-mode',
              'simple']

IRB.conf[:SAVE_HISTORY] = 50
IRB.conf[:HISTORY_FILE] = '.irb-history'

require 'calabash-cucumber/operations'

extend Calabash::Cucumber::Operations

def embed(x,y=nil,z=nil)
  puts "Screenshot at #{x}"
end

require "calabash-cucumber"

def preferences
  Calabash::Cucumber::Preferences.new
end

def disable_usage_tracking
  preferences.usage_tracking = "none"
  puts "Calabash will not collect usage information."
  "none"
end

def enable_usage_tracking(level="system_info")
  preferences.usage_tracking = level
  puts "Calabash will collect statistics using the '#{level}' rule."
  level
end
```

**Comment by jmoody** [comment]
This will be fixed in the next prerelease.

**Comment by jmoody** [comment]
Found the problem: cbcb3154d11e45349fe682dc680dc570e6f6d13b
